<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateCabins extends Migration{
	public function up(){ 
		Schema::create('pavilions', function (Blueprint $table) { 
			$table->bigIncrements('code');
			$table->timestamps();
		});
		Schema::create('classrooms', function (Blueprint $table) { 
			$table->bigIncrements('code');
			$table->unsignedBigInteger('code_pavilion');
			$table->foreign('code_pavilion')->references('code')->on('pavilions');
			$table->timestamps();
		});
 		Schema::create('cabins', function (Blueprint $table) { 
			$table->bigIncrements('code');
			$table->String('location');
			$table->unsignedBigInteger('code_pavilion');
			$table->foreign('code_pavilion')->references('code')->on('pavilions');
			$table->unsignedBigInteger('code_classroom');
			$table->foreign('code_classroom')->references('code')->on('classrooms');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}