<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateCandidates extends Migration{
	public function up(){ 
		Schema::create('users', function (Blueprint $table) { 
			$table->bigIncrements('dni');
			$table->String('name');
			$table->String('last_name');
			$table->Integer('age');
			$table->timestamps();
		});
 		Schema::create('candidates', function (Blueprint $table) { 
			$table->bigIncrements('code');
			$table->unsignedBigInteger('dni_user');
			$table->foreign('dni_user')->references('dni')->on('users');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}