<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateElectors extends Migration{
	public function up(){ 
 		Schema::create('electors', function (Blueprint $table) { 
			$table->bigIncrements('code');
			$table->unsignedBigInteger('dni_user');
			$table->foreign('dni_user')->references('dni')->on('users');
			$table->boolean('state');
			$table->String('mail');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}