<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class candidate extends Model{
    public function vote(){ return $this->hasMany('App\Models\vote'); }
}