<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class classroom extends Model{
public function cabin(){ return $this->hasOne('App\Models\cabin'); }
public function pavilion(){ return $this->belongsTo('App\Models\pavilion'); }
}