<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class pavilion extends Model{
    public function classroom(){ return $this->hasMany('App\Models\classroom'); }
}