<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class vote extends Model{
public function elector(){ return $this->belongsTo('App\Models\elector'); }
public function candidate(){ return $this->belongsTo('App\Models\candidate'); }
public function cabin(){ return $this->belongsTo('App\Models\cabin'); }
}